package com.iliauni.usersyncglobalservice.idp;

import com.iliauni.usersyncglobalservice.model.User;
import com.iliauni.usersyncglobalservice.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A class implementing {@link UserDbSyncHandler} for synchronizing users
 * in a local database context.
 */
@Component
public class GenericUserDbSyncHandler implements UserDbSyncHandler {
    private final UserService userService;

    @Autowired
    public GenericUserDbSyncHandler(UserService userService) {
        this.userService = userService;
    }

    @Override
    public void sync(Map<String, List<Optional<User>>> differenceMap) {
        buildSyncFlagsMap().forEach((key, flags) -> {
            Boolean isNew = flags[0];

            differenceMap.getOrDefault(key, new ArrayList<>()).forEach(user -> {
                user.ifPresent(u -> {
                    if (isNew) {
                        userService.save(Optional.of(u));
                    } else {
                        userService.deleteById(u.getUsername());
                    }
                });
            });
        });
    }

    /**
     * Builds a map containing boolean representations of flags,
     * which are supposed to be passed to synchronization methods.
     * Such as: "new", "altered", "missing", etc.
     * The keys are meant to match the keys of difference map, generated by DifferenceCalculator.
     * This exists for the sake of reducing boilerplate and adding some scalability.
     *
     * @return a map of boolean representations of DifferenceCalculator map's flags
     */
    private Map<String, Boolean[]> buildSyncFlagsMap() {
        return Map.of(
                "new", new Boolean[]{true, false},
                "altered", new Boolean[]{false, true},
                "missing", new Boolean[]{false, false}
        );
    }
}
