# Variables to inject in Java code

# The FreeIPA API endpoint for general requests (excluding hostname, ip, port, and protocol)
ipaApiEndpoint: ${IPA_API_ENDPOINT:/ipa/session/json}
# The FreeIPA API endpoint to get cookies for auth (excluding hostname, ip, port, and protocol)
ipaApiAuthEndpoint: ${IPA_API_AUTH_ENDPOINT:/ipa/session/login_password}

# The name of the admin-cli Keycloak client
kcAdminCliClientId: ${KC_ADMIN_CLI_CLIENT_ID:admin-cli}

# The role name of the user that can access secured endpoints
principalRoleName: ${PRINCIPAL_ROLE_NAME:administrator}

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
    level:
        org:
            springframework:
                security: warn
        root: warn
server:
    port: ${SERVER_PORT:8000}
spring:
    application:
        name: idp-sync-service
    cloud:
        loadbalancer:
            cache:
                enabled: true
            enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DATASOURCE_PASSWORD}
        url: jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_NAME}
        username: ${DATASOURCE_USERNAME}
    devtools:
        livereload:
            enabled: true
            port: ${LIVERELOAD_PORT:35730}
    main:
        banner-mode: 'off'
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URL}
                opaquetoken:
                    client-id: ${OAUTH2_PROVIDER_CLIENT_ID}
                    client-secret: ${OAUTH2_PROVIDER_CLIENT_SECRET}
                    introspection-uri: ${OAUTH2_PROVIDER_INTROSPECTION_URL}
    jpa:
        open-in-view: true