CREATE TABLE api_access_kc_client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    client_secret      VARCHAR(255),
    CONSTRAINT pk_apiaccesskcclient PRIMARY KEY (id)
);

CREATE TABLE api_access_kc_client_refresh_tokens
(
    api_access_kc_client_id VARCHAR(255) NOT NULL,
    refresh_tokens_id       BIGINT       NOT NULL
);

CREATE TABLE cookie
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cookie        VARCHAR(512),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    cookie_jar    VARCHAR(255),
    CONSTRAINT pk_cookie PRIMARY KEY (id)
);

CREATE TABLE cookie_client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    CONSTRAINT pk_cookieclient PRIMARY KEY (id)
);

CREATE TABLE cookie_client_cookies
(
    cookie_client_id VARCHAR(255) NOT NULL,
    cookies_id       BIGINT       NOT NULL
);

CREATE TABLE ipa_client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    CONSTRAINT pk_ipaclient PRIMARY KEY (id)
);

CREATE TABLE ipa_client_cookies
(
    ipa_client_id VARCHAR(255) NOT NULL,
    cookies_id    BIGINT       NOT NULL
);

CREATE TABLE kc_client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    client_secret      VARCHAR(255),
    CONSTRAINT pk_kcclient PRIMARY KEY (id)
);

CREATE TABLE kc_client_refresh_tokens
(
    kc_client_id      VARCHAR(255) NOT NULL,
    refresh_tokens_id BIGINT       NOT NULL
);

CREATE TABLE oauth2client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    client_secret      VARCHAR(255),
    CONSTRAINT pk_oauth2client PRIMARY KEY (id)
);

CREATE TABLE oauth2client_refresh_tokens
(
    oauth2client_id   VARCHAR(255) NOT NULL,
    refresh_tokens_id BIGINT       NOT NULL
);

CREATE TABLE sync_user
(
    username  VARCHAR(255) NOT NULL,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_sync_user PRIMARY KEY (username)
);

CREATE TABLE token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype         VARCHAR(31),
    token         VARCHAR(2560),
    expires_in    INTEGER,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

CREATE TABLE usergroup
(
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_usergroup PRIMARY KEY (name)
);

CREATE TABLE usergroup_user
(
    user_username  VARCHAR(255) NOT NULL,
    usergroup_name VARCHAR(255) NOT NULL
);

CREATE TABLE win_client
(
    id                 VARCHAR(255) NOT NULL,
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    client_secret      VARCHAR(255),
    CONSTRAINT pk_winclient PRIMARY KEY (id)
);

CREATE TABLE win_client_refresh_tokens
(
    win_client_id     VARCHAR(255) NOT NULL,
    refresh_tokens_id BIGINT       NOT NULL
);

ALTER TABLE api_access_kc_client_refresh_tokens
    ADD CONSTRAINT uc_api_access_kc_client_refresh_tokens_refreshtokens UNIQUE (refresh_tokens_id);

ALTER TABLE cookie_client_cookies
    ADD CONSTRAINT uc_cookie_client_cookies_cookies UNIQUE (cookies_id);

ALTER TABLE ipa_client_cookies
    ADD CONSTRAINT uc_ipa_client_cookies_cookies UNIQUE (cookies_id);

ALTER TABLE kc_client_refresh_tokens
    ADD CONSTRAINT uc_kc_client_refresh_tokens_refreshtokens UNIQUE (refresh_tokens_id);

ALTER TABLE oauth2client_refresh_tokens
    ADD CONSTRAINT uc_oauth2client_refresh_tokens_refreshtokens UNIQUE (refresh_tokens_id);

ALTER TABLE win_client_refresh_tokens
    ADD CONSTRAINT uc_win_client_refresh_tokens_refreshtokens UNIQUE (refresh_tokens_id);

ALTER TABLE api_access_kc_client_refresh_tokens
    ADD CONSTRAINT fk_apiacckcclireftok_on_api_access_kc_client FOREIGN KEY (api_access_kc_client_id) REFERENCES api_access_kc_client (id);

ALTER TABLE api_access_kc_client_refresh_tokens
    ADD CONSTRAINT fk_apiacckcclireftok_on_refresh_token FOREIGN KEY (refresh_tokens_id) REFERENCES token (id);

ALTER TABLE cookie_client_cookies
    ADD CONSTRAINT fk_cooclicoo_on_cookie FOREIGN KEY (cookies_id) REFERENCES cookie (id);

ALTER TABLE ipa_client_cookies
    ADD CONSTRAINT fk_ipaclicoo_on_cookie FOREIGN KEY (cookies_id) REFERENCES cookie (id);

ALTER TABLE ipa_client_cookies
    ADD CONSTRAINT fk_ipaclicoo_on_ipa_client FOREIGN KEY (ipa_client_id) REFERENCES ipa_client (id);

ALTER TABLE kc_client_refresh_tokens
    ADD CONSTRAINT fk_kcclireftok_on_kc_client FOREIGN KEY (kc_client_id) REFERENCES kc_client (id);

ALTER TABLE kc_client_refresh_tokens
    ADD CONSTRAINT fk_kcclireftok_on_refresh_token FOREIGN KEY (refresh_tokens_id) REFERENCES token (id);

ALTER TABLE oauth2client_refresh_tokens
    ADD CONSTRAINT fk_oaureftok_on_refresh_token FOREIGN KEY (refresh_tokens_id) REFERENCES token (id);

ALTER TABLE usergroup_user
    ADD CONSTRAINT fk_useuse_on_user FOREIGN KEY (user_username) REFERENCES sync_user (username);

ALTER TABLE usergroup_user
    ADD CONSTRAINT fk_useuse_on_usergroup FOREIGN KEY (usergroup_name) REFERENCES usergroup (name);

ALTER TABLE win_client_refresh_tokens
    ADD CONSTRAINT fk_winclireftok_on_refresh_token FOREIGN KEY (refresh_tokens_id) REFERENCES token (id);

ALTER TABLE win_client_refresh_tokens
    ADD CONSTRAINT fk_winclireftok_on_win_client FOREIGN KEY (win_client_id) REFERENCES win_client (id);