CREATE TABLE client
(
    id                 VARCHAR(255) NOT NULL,
    dtype              VARCHAR(31),
    fqdn               VARCHAR(255),
    principal_username VARCHAR(255),
    principal_password VARCHAR(255),
    client_secret      VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE cookie_jar
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cookie        VARCHAR(512),
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    cookie_jar    VARCHAR(255),
    CONSTRAINT pk_cookiejar PRIMARY KEY (id)
);

CREATE TABLE null_cookie_jars
(
    ipa_client_id  VARCHAR(255) NOT NULL,
    cookie_jars_id BIGINT       NOT NULL
);

CREATE TABLE null_refresh_tokens
(
    oauth2client_id   VARCHAR(255) NOT NULL,
    refresh_tokens_id BIGINT       NOT NULL
);

CREATE TABLE token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype         VARCHAR(31),
    token         VARCHAR(2560),
    expires_in    INTEGER,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    username  VARCHAR(255) NOT NULL,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (username)
);

CREATE TABLE usergroup
(
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_usergroup PRIMARY KEY (name)
);

CREATE TABLE usergroup_user
(
    user_username  VARCHAR(255) NOT NULL,
    usergroup_name VARCHAR(255) NOT NULL
);

ALTER TABLE null_cookie_jars
    ADD CONSTRAINT uc_null_cookie_jars_cookiejars UNIQUE (cookie_jars_id);

ALTER TABLE null_refresh_tokens
    ADD CONSTRAINT uc_null_refresh_tokens_refreshtokens UNIQUE (refresh_tokens_id);

ALTER TABLE cookie_jar
    ADD CONSTRAINT FK_COOKIEJAR_ON_COOKIE_JAR FOREIGN KEY (cookie_jar) REFERENCES client (id);

ALTER TABLE null_cookie_jars
    ADD CONSTRAINT fk_nulcoojar_on_cookie_jar FOREIGN KEY (cookie_jars_id) REFERENCES cookie_jar (id);

ALTER TABLE null_cookie_jars
    ADD CONSTRAINT fk_nulcoojar_on_ipa_client FOREIGN KEY (ipa_client_id) REFERENCES client (id);

ALTER TABLE null_refresh_tokens
    ADD CONSTRAINT fk_nulreftok_on_oauth2_client FOREIGN KEY (oauth2client_id) REFERENCES client (id);

ALTER TABLE null_refresh_tokens
    ADD CONSTRAINT fk_nulreftok_on_refresh_token FOREIGN KEY (refresh_tokens_id) REFERENCES token (id);

ALTER TABLE usergroup_user
    ADD CONSTRAINT fk_useuse_on_user FOREIGN KEY (user_username) REFERENCES "user" (username);

ALTER TABLE usergroup_user
    ADD CONSTRAINT fk_useuse_on_usergroup FOREIGN KEY (usergroup_name) REFERENCES usergroup (name);