CREATE TABLE user_sync_event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usersyncevent PRIMARY KEY (id)
);

CREATE TABLE user_sync_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sync_event_id BIGINT,
    user_username VARCHAR(255),
    status        VARCHAR(255),
    CONSTRAINT pk_usersyncstatus PRIMARY KEY (id)
);

CREATE TABLE usergroup_sync_event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usergroupsyncevent PRIMARY KEY (id)
);

CREATE TABLE usergroup_sync_status
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sync_event_id  BIGINT,
    usergroup_name VARCHAR(255),
    status         VARCHAR(255),
    CONSTRAINT pk_usergroupsyncstatus PRIMARY KEY (id)
);

ALTER TABLE usergroup_sync_status
    ADD CONSTRAINT FK_USERGROUPSYNCSTATUS_ON_SYNC_EVENT FOREIGN KEY (sync_event_id) REFERENCES usergroup_sync_event (id);

ALTER TABLE usergroup_sync_status
    ADD CONSTRAINT FK_USERGROUPSYNCSTATUS_ON_USERGROUP_NAME FOREIGN KEY (usergroup_name) REFERENCES usergroup (name);

ALTER TABLE user_sync_status
    ADD CONSTRAINT FK_USERSYNCSTATUS_ON_SYNC_EVENT FOREIGN KEY (sync_event_id) REFERENCES user_sync_event (id);

ALTER TABLE user_sync_status
    ADD CONSTRAINT FK_USERSYNCSTATUS_ON_USER_USERNAME FOREIGN KEY (user_username) REFERENCES sync_user (username);
